# Database credentials
database:
  connections: 10
  db-name: "postgres"
  host: "localhost"
  pass: "postgres"
  port: 5432
  user: "postgres"

# Server configurations
server:
  cors-allowed-clients: ["http://localhost:5173"]
  environment: "dev"
  host: "localhost"
  port: 8080
  protocol: "http"
